spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**
          filters:
            - name: Retry
              args:
                retries: 2
                methods: GET
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/carts/**,/api/orders/**
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
logging:
  level:
    org.springframework.cloud.gateway: INFO

