spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/api/carts/**,/api/orders/**,/api/auth/**
        - id: ai-insights-service
          uri: http://ai-insights-service:8084
          predicates:
            - Path=/api/ai-insights/**
        - id: ui
          uri: http://ui:8085
          predicates:
            - Path=/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: 6379
      timeout: 2000ms
  tracing:
    zipkin:
      base-url: http://zipkin:9411
    sampling:
      probability: 1.0

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.valven.ecommerce: INFO
    org.springframework.web: WARN