spring:
  application:
    name: api-gateway
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
logging:
  level:
    org.springframework.cloud.gateway: INFO
resilience4j:
  circuitbreaker:
    instances:
      products:
        slidingWindowSize: 10
        failureRateThreshold: 50
      orders:
        slidingWindowSize: 10
        failureRateThreshold: 50
---
spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: products
            - name: Retry
              args:
                retries: 2
                methods: GET
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/carts/**,/api/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orders

