groups:
- name: valven-ecommerce-alerts
  rules:
  # High Error Rate Alert
  - alert: HighErrorRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
    for: 2m
    labels:
      severity: critical
      service: "{{ $labels.service }}"
    annotations:
      summary: "High error rate detected"
      description: "Service {{ $labels.service }} has error rate of {{ $value }} errors per second"
      runbook_url: "https://valven.com/runbooks/high-error-rate"

  # High Response Time Alert
  - alert: HighResponseTime
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
    for: 5m
    labels:
      severity: warning
      service: "{{ $labels.service }}"
    annotations:
      summary: "High response time detected"
      description: "Service {{ $labels.service }} has 95th percentile response time of {{ $value }}s"
      runbook_url: "https://valven.com/runbooks/high-response-time"

  # Service Down Alert
  - alert: ServiceDown
    expr: up{job=~"valven-.*"} == 0
    for: 1m
    labels:
      severity: critical
      service: "{{ $labels.job }}"
    annotations:
      summary: "Service is down"
      description: "Service {{ $labels.job }} has been down for more than 1 minute"
      runbook_url: "https://valven.com/runbooks/service-down"

  # High Memory Usage Alert
  - alert: HighMemoryUsage
    expr: (jvm_memory_used_bytes / jvm_memory_max_bytes) > 0.8
    for: 5m
    labels:
      severity: warning
      service: "{{ $labels.service }}"
    annotations:
      summary: "High memory usage detected"
      description: "Service {{ $labels.service }} is using {{ $value | humanizePercentage }} of available memory"
      runbook_url: "https://valven.com/runbooks/high-memory-usage"

  # High CPU Usage Alert
  - alert: HighCPUUsage
    expr: rate(process_cpu_seconds_total[5m]) > 0.8
    for: 5m
    labels:
      severity: warning
      service: "{{ $labels.service }}"
    annotations:
      summary: "High CPU usage detected"
      description: "Service {{ $labels.service }} is using {{ $value | humanizePercentage }} of available CPU"
      runbook_url: "https://valven.com/runbooks/high-cpu-usage"

  # Database Connection Pool Exhaustion
  - alert: DatabaseConnectionPoolExhaustion
    expr: hikaricp_connections_active / hikaricp_connections_max > 0.9
    for: 2m
    labels:
      severity: critical
      service: "{{ $labels.service }}"
    annotations:
      summary: "Database connection pool nearly exhausted"
      description: "Service {{ $labels.service }} is using {{ $value | humanizePercentage }} of database connections"
      runbook_url: "https://valven.com/runbooks/database-connection-pool"

  # Redis Connection Issues
  - alert: RedisConnectionIssues
    expr: redis_up == 0
    for: 1m
    labels:
      severity: critical
      service: "{{ $labels.service }}"
    annotations:
      summary: "Redis connection issues"
      description: "Service {{ $labels.service }} cannot connect to Redis"
      runbook_url: "https://valven.com/runbooks/redis-connection"

  # JVM Garbage Collection Issues
  - alert: JVMGarbageCollectionIssues
    expr: rate(jvm_gc_pause_seconds_total[5m]) > 0.1
    for: 5m
    labels:
      severity: warning
      service: "{{ $labels.service }}"
    annotations:
      summary: "JVM garbage collection issues"
      description: "Service {{ $labels.service }} has high GC pause time of {{ $value }}s per second"
      runbook_url: "https://valven.com/runbooks/jvm-gc-issues"

  # Circuit Breaker Open
  - alert: CircuitBreakerOpen
    expr: circuit_breaker_state{state="OPEN"} == 1
    for: 0m
    labels:
      severity: critical
      service: "{{ $labels.service }}"
    annotations:
      summary: "Circuit breaker is open"
      description: "Circuit breaker for {{ $labels.service }} is open"
      runbook_url: "https://valven.com/runbooks/circuit-breaker-open"

  # Rate Limiting Triggered
  - alert: RateLimitingTriggered
    expr: rate(rate_limiter_rejected_total[5m]) > 0
    for: 1m
    labels:
      severity: warning
      service: "{{ $labels.service }}"
    annotations:
      summary: "Rate limiting is being triggered"
      description: "Service {{ $labels.service }} is rejecting requests due to rate limiting"
      runbook_url: "https://valven.com/runbooks/rate-limiting"

  # Authentication Failures
  - alert: HighAuthenticationFailures
    expr: rate(authentication_failures_total[5m]) > 10
    for: 2m
    labels:
      severity: warning
      service: "{{ $labels.service }}"
    annotations:
      summary: "High authentication failure rate"
      description: "Service {{ $labels.service }} has {{ $value }} authentication failures per second"
      runbook_url: "https://valven.com/runbooks/authentication-failures"

  # Disk Space Low
  - alert: DiskSpaceLow
    expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
    for: 5m
    labels:
      severity: critical
      node: "{{ $labels.instance }}"
    annotations:
      summary: "Disk space is low"
      description: "Node {{ $labels.instance }} has only {{ $value | humanizePercentage }} disk space available"
      runbook_url: "https://valven.com/runbooks/disk-space-low"

  # Pod Restart Alert
  - alert: PodRestarting
    expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
    for: 0m
    labels:
      severity: warning
      pod: "{{ $labels.pod }}"
      namespace: "{{ $labels.namespace }}"
    annotations:
      summary: "Pod is restarting"
      description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting"
      runbook_url: "https://valven.com/runbooks/pod-restarting"

  # Network Latency High
  - alert: NetworkLatencyHigh
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="gateway"}[5m])) > 1
    for: 5m
    labels:
      severity: warning
      service: "gateway"
    annotations:
      summary: "High network latency"
      description: "Gateway service has 95th percentile latency of {{ $value }}s"
      runbook_url: "https://valven.com/runbooks/network-latency"

  # Business Metrics Alerts
  - alert: LowOrderVolume
    expr: rate(orders_created_total[1h]) < 1
    for: 30m
    labels:
      severity: warning
    annotations:
      summary: "Low order volume"
      description: "Order creation rate is {{ $value }} orders per hour"
      runbook_url: "https://valven.com/runbooks/low-order-volume"

  - alert: HighCartAbandonmentRate
    expr: rate(cart_abandoned_total[1h]) / rate(cart_created_total[1h]) > 0.8
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "High cart abandonment rate"
      description: "Cart abandonment rate is {{ $value | humanizePercentage }}"
      runbook_url: "https://valven.com/runbooks/cart-abandonment"